
import { ScrollView, Alert, StatusBar, StyleSheet} from 'react-native';
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
    accountDesc: {
        top: 30
    },
    account: {
        resizeMode: 'stretch',
        width: 170,
        height: 170,
        left: 100,
        top: 15,
    },
    inqiuryField: {
        top: 35,
        marginTop: 10,
        marginBottom: 10,
        margin: 27,
        padding: 10,
        borderWidth: 1.0,
        borderColor: '#6610f2',
        fontSize: 17,
        fontFamily: "WorkSans_400Regular",
    },
    itemHeader: {
        fontFamily: "WorkSans_700Bold",
    },
    contactIcons: {
        bottom: 270,
    },
    services: {
        marginTop: 50,
    },
    contact: {
        bottom: 280,
    },
    column1: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'flex-start',
        top: 10,
        left: 10,
    },
    column2: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'flex-start',
        top: 25,
        left: 10,
    },
    items: {
        width: '25%',
    },
    itemDesc: {
        width: '25%',
        right: 30,
        fontFamily: "WorkSans_400Regular",
    },
    header: {
        textAlign: 'right',
        fontSize: 18,
        fontFamily: "WorkSans_700Bold",
        color: "#5f55a5",
        right: 25,
        bottom: 100,
    },
    header1: {
        textAlign: 'left',
        fontSize: 18,
        fontFamily: "WorkSans_700Bold",
        color: "#5f55a5",
        left: 25,
        bottom: 190,
    },
    header2: {
        textAlign: 'right',
        fontSize: 18,
        fontFamily: "WorkSans_700Bold",
        color: "#5f55a5",
        right: 25,
        bottom: 280,
    },
    header3: {
        textAlign: 'left',
        fontSize: 18,
        fontFamily: "WorkSans_700Bold",
        color: "#5f55a5",
        left: 25,
        bottom: 345,
    },
    headerService: {
        textAlign: 'center',
        fontSize: 18,
        fontFamily: "WorkSans_700Bold",
        color: "#5f55a5",
        marginTop: 15,
    },
    desc: {
        fontSize: 14,
        fontFamily: "WorkSans_400Regular",
        marginHorizontal: 50,
        bottom: 100,
        textAlign: 'right',
        left: 25,
    },
    desc1: {
        fontSize: 14,
        fontFamily: "WorkSans_400Regular",
        marginHorizontal: 50,
        bottom: 190,
        textAlign: 'left',
        right: 25,
    },
    desc2: {
        fontSize: 14,
        fontFamily: "WorkSans_400Regular",
        marginHorizontal: 50,
        bottom: 270,
        textAlign: 'right',
        left: 25,
    },
    desc3: {
        fontSize: 14,
        fontFamily: "WorkSans_400Regular",
        marginHorizontal: 50,
        bottom: 340,
        textAlign: 'left',
        right: 25,
    },
    item: {
        backgroundColor: 'rgba(255, 255, 255, 0.45)',
        padding: 20,
        marginVertical: 8,
        marginHorizontal: 16,
        top: 30,
    },
    text: {
        textAlign: 'center',
        fontSize: 17,
        fontFamily: "WorkSans_400Regular",
        marginHorizontal: 20,
        top: 30,
    },
    text1: {
        textAlign: 'center',
        fontSize: 15,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        top: 20,
        color: '#6610f2',
    },
    text2: {
        textAlign: 'center',
        fontSize: 15,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: '#6610f2',
    },
    text4: {
        textAlign: 'center',
        fontSize: 15,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: '#6610f2',
        top: 30,
    },
    text5: {
        textAlign: 'center',
        fontSize: 29,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: 'black',
        top: 30,
        marginBottom: 20,
    },
    text3: {
        textAlign: 'center',
        fontSize: 29,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: 'black',
    },
    text6: {
        textAlign: 'center',
        fontSize: 15,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: '#6610f2',
    },
    text7: {
        textAlign: 'center',
        fontSize: 29,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: 'black',
    },
    text8: {
        textAlign: 'center',
        fontSize: 15,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: '#6610f2',
    },
    text9: {
        textAlign: 'center',
        fontSize: 29,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 10,
        color: 'black',
        marginBottom: 20,
    },
    text10: {
        textAlign: 'center',
        fontSize: 15,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 20,
        color: '#6610f2',
        top: 40,
    },
    text11: {
        textAlign: 'center',
        fontSize: 29,
        fontFamily: "WorkSans_700Bold",
        marginHorizontal: 10,
        color: 'black',
        marginBottom: 60,
        top: 40,
    },
    serviceView1: {
        bottom: 30,
    },
    container: {
        flex: 1,
        paddingTop: StatusBar.currentHeight,
    },
    scrollView: {
        marginBottom: 5
    },
    input1: {
        top: 50,
        margin: 60,
        padding: 10,
        borderBottomWidth: 1.0,
        borderBottomColor: '#6610f2',
        fontSize: 17,
        fontFamily: "WorkSans_400Regular",
    },
    input2: {
        bottom: 50,
        margin: 60,
        padding: 10,
        borderBottomWidth: 1.0,
        borderBottomColor: '#6610f2',
        fontSize: 17,
        fontFamily: "WorkSans_400Regular",
    },
    regIcons: {
        position: 'absolute',
        bottom: 180,
        resizeMode: 'stretch',
        left: 75,
    },
    loginImage: {
        position: 'absolute',
        top: 40,
        height: 320,
        width: 320,
        resizeMode: 'stretch',
        marginLeft: 40,
    },
    homeImage: {
        resizeMode: 'stretch',
        height: 320,
        width: 380,
    },
    services1Pic: {
        resizeMode: 'stretch',
        height: 360,
        width: 380,
    },
    services2Pic: {
        resizeMode: 'stretch',
        height: 370,
        width: 420,
        right: 18,
        top: 0,
    },
    homePic: {
        position: 'relative',
        height: 70,
        width: 370,
        top: 10,
    },
    servicesPic: {
        height: 310,
        width: 300,
        marginLeft: 40,
        top: 40,
    },
    servicesPic1: {
        top: 20,
        opacity: 0.4,
        borderRadius: 20,
    },
    servicesPic2: {
        bottom: 70,
        opacity: 0.4,
        borderRadius: 20,
    },
    servicesPic3: {
        bottom: 160,
        opacity: 0.4,
        borderRadius: 20,
    },
    datePos: {
        bottom: 200,
    },
    timePos: {
        bottom: 160,
    },
    endPos: {
        top: 600,
    },
    servicesPic4: {
        bottom: 230,
        opacity: 0.4,
        borderRadius: 20,
    },
    aboutPic: {
        borderRadius: 50,
        height: 300,
        width: 300,
        right: 120,
        top: 40,
    },
    descService: {
        textAlign: 'center',
        justifyContent: 'center',
        marginHorizontal: 20,
        fontFamily: "WorkSans_400Regular",
        fontSize: 16,
    },
    descService1: {
        textAlign: 'center',
        justifyContent: 'center',
        marginHorizontal: 20,
        fontFamily: "WorkSans_400Regular",
        fontSize: 16,
    },
    apptSummary: {
        textAlign: 'left',
        justifyContent: 'center',
        marginHorizontal: 20,
        fontFamily: "WorkSans_400Regular",
        fontSize: 16,
    },
    apptSummary1: {
        textAlign: 'left',
        justifyContent: 'center',
        marginHorizontal: 20,
        fontFamily: "WorkSans_700Bold",
        fontSize: 16,
    },
    bg: {
        resizeMode: "stretch",
        justifyContent: "center",
        width: 400,
        height: 900,
    },
    SubmitButtonStyle: {
        position: 'absolute',
        top: 520,
        paddingTop: 12,
        paddingBottom: 12,
        width: 200,
        backgroundColor: '#6610f2',
        borderRadius: 30,
        right: 105,
    },
    SubmitButtonStyle1: {
        position: 'relative',
        left: 80,
        paddingTop: 12,
        paddingBottom: 12,
        width: 210,
        backgroundColor: '#6610f2',
        borderRadius: 30,
        top: 45,
    },
    SubmitButtonStyle3: {
        position: 'absolute',
        top: 330,
        paddingTop: 12,
        paddingBottom: 12,
        width: 200,
        backgroundColor: '#6610f2',
        borderRadius: 30,
        right: 97,
    },
    SubmitButtonStyle4: {
        position: 'relative',
        left: 80,
        paddingTop: 12,
        paddingBottom: 12,
        width: 210,
        backgroundColor: '#6610f2',
        borderRadius: 30,
        bottom: 250,
    },
    SubmitButtonStyle5: {
        position: 'relative',
        left: 80,
        paddingTop: 12,
        paddingBottom: 12,
        width: 210,
        backgroundColor: 'white',
        borderRadius: 30,
        bottom: 230,
    },
    TextStyle: {
        fontFamily: "WorkSans_400Regular",
        color: 'white',
        textAlign: 'center',
        fontSize: 18,
    },
    TextStyle1: {
        fontFamily: "WorkSans_400Regular",
        color: 'gray',
        textAlign: 'center',
        fontSize: 16,
    },
    blank: {
        marginBottom: 250,
    },
    TextStyle2: {
        fontFamily: "WorkSans_400Regular",
        color: '#6610f2',
        fontSize: 16,
        textAlign: 'center',
    },
    TextStyle3: {
        fontFamily: "WorkSans_700Bold",
        color: '#6610f2',
        fontSize: 14,
        top: 10,
    },
    TextStyle4: {
        fontFamily: "WorkSans_700Bold",
        color: '#6610f2',
        fontSize: 14,
        top: 15,
    },
    TextStyle5: {
        fontFamily: "WorkSans_700Bold",
        color: '#6610f2',
        fontSize: 14,
        top: 15,
    },
    TextStyle6: {
        fontFamily: "WorkSans_400Regular",
        color: '#6610f2',
        textAlign: 'center',
        fontSize: 18,
    },
    appointmentImage: {
        opacity: 0.5,
        width: 340,
        height: 930,
        resizeMode: 'stretch',
        top: 75,
        left: 17.5,
    },
    aptView: {
        top: 50,
    },
    aptView1: {
        bottom: 550,
    },
    input3: {
        marginVertical: 15,
        marginHorizontal: 45,
        bottom: 270,
        padding: 10,
        borderBottomWidth: 1.0,
        borderBottomColor: '#6610f2',
        fontSize: 16,
        fontFamily: "Roboto",
    },
    input4: {
        marginVertical: 15,
        marginHorizontal: 45,
        bottom: 140,
        padding: 10,
        borderWidth: 1.0,
        borderColor: '#6610f2',
        fontSize: 16,
        fontFamily: "Roboto",
    },
    SubmitButtonStyle2: {
        position: 'relative',
        left: 80,
        paddingTop: 12,
        paddingBottom: 12,
        width: 210,
        backgroundColor: '#6610f2',
        borderRadius: 30,
        bottom: 250,
    },
    SubmitButtonStyle6: {
        position: 'relative',
        left: 80,
        paddingTop: 12,
        paddingBottom: 12,
        width: 210,
        backgroundColor: '#6610f2',
        borderRadius: 30,
        bottom: 80,
    },
    appointmentImage1: {
        position: 'relative',
        bottom: 820,
        left: 90,
        height: 140,
        width: 180,
        opacity: 0.8,
    },
    customBg:{
        flex:1,
        flexDirection:"column"
    }
})

export default styles;